name: yowshare
description: YowShare - Cross-platform local file sharing

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.0
  receive_sharing_intent: ^1.5.5
  # File Picking (Cross-platform)
  file_picker: ^8.0.0

  # Permissions (Mobile only, but safe for Windows)
  permission_handler: ^11.3.0

  # Notifications (Mobile only)
  flutter_local_notifications: ^17.1.2

  # Networking (built-in UDP + HttpServer)
  http: ^1.2.0

  # Device Info
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
